(setf path "C:\\Documents and Settings\\john\\My Documents\\karim\\PWLisp\\")
;(setf path "./")

(load (concatenate 'string path "sapa-package.lisp"))
(load (concatenate 'string path "utilities.lisp"))
(load (concatenate 'string path "basic-math.lisp"))
(load (concatenate 'string path "basic-statistics.lisp"))
(load (concatenate 'string path "dft-and-fft.lisp"))
(load (concatenate 'string path "tapers.lisp"))
(load (concatenate 'string path "random.lisp"))
(load (concatenate 'string path "acvs.fsl"))
(load (concatenate 'string path "nonparametric.lisp"))
(load (concatenate 'string path "parametric.lisp"))
(load (concatenate 'string path "multitaper.lisp"))
(load (concatenate 'string path "harmonic.lisp"))
(in-package :SAPA)
