(load "D:\\My Documents\\PWLisp\\sapa-package.fsl") 
(load "D:\\My Documents\\PWLisp\\utilities.fsl") 
(load "D:\\My Documents\\PWLisp\\basic-math.fsl")
(load "D:\\My Documents\\PWLisp\\basic-statistics.fsl")
(load "D:\\My Documents\\PWLisp\\dft-and-fft.fsl")
(load "D:\\My Documents\\PWLisp\\dft-and-fft.fsl")
(load "D:\\My Documents\\PWLisp\\tapers.fsl")
(load "D:\\My Documents\\PWLisp\\random.fsl")
(load "D:\\My Documents\\PWLisp\\acvs.fsl")
(load "D:\\My Documents\\PWLisp\\nonparametric.fsl")
(load "D:\\My Documents\\PWLisp\\parametric.fsl")
(load "D:\\My Documents\\PWLisp\\multitaper.fsl")
(load "D:\\My Documents\\PWLisp\\harmonic.fsl")
(in-package :SAPA)