(load "D:\\My Documents\\PWLisp\\sapa-package.lisp") 
(load "D:\\My Documents\\PWLisp\\utilities.lisp") 
(load "D:\\My Documents\\PWLisp\\basic-math.lisp")
(load "D:\\My Documents\\PWLisp\\basic-statistics.lisp")
(load "D:\\My Documents\\PWLisp\\dft-and-fft.lisp")
(load "D:\\My Documents\\PWLisp\\dft-and-fft.lisp")
(load "D:\\My Documents\\PWLisp\\tapers.lisp")
(load "D:\\My Documents\\PWLisp\\random.lisp")
(load "D:\\My Documents\\PWLisp\\acvs.lisp")
(load "D:\\My Documents\\PWLisp\\parametric.lisp")
(load "D:\\My Documents\\PWLisp\\nonparametric.lisp")
(load "D:\\My Documents\\PWLisp\\multitaper.lisp")
(load "D:\\My Documents\\PWLisp\\harmonic.lisp")
(in-package :SAPA)